### PR TITLE
APP-3101: Clean truststore files using in generators

### PR DESCRIPTION
**Pull request by symphony-hong**
### Ticket
[APP-3101](https://perzoinc.atlassian.net/browse/APP-3101)

### Description
Cleaning the truststore files using in generators. Now one truststore and 
truststore in pem format will be shared across the generators

Temporarily remove code coverage threshold for bdk folder due to the
issue of relative path used in jest configuration. After adding some
ut for legacy sdk generators, the jest coverage didn't find the coverage
data for the path './generators/bdk/**/*.js'.

### Dependencies
List the other pull requests that should be merged before/along this one.

### Checklist
- [x] Referenced a ticket in the PR title and in the corresponding section
- [x] Filled properly the description and dependencies, if any
- [x] Public functions properly commented

### CODE REVIEW

**Review by symphony-youri — COMMENTED** [review]
Could we provide a README in the truststore folder on how to edit it?
(I always have to google for the commands to add a certificate)

**Comment by symphony-hong** [comment]
> Could we provide a README in the truststore folder on how to edit it?
> (I always have to google for the commands to add a certificate)

Good idea! I always have to google it as well. :)

**Review by symphony-youri — COMMENTED** [review]
Nice work on adding the test, about the jest issue is it something we can try to fix? is there an error message a failure or it just does not work as expected ( what did we change that could affect it?)

**Comment by symphony-hong** [comment]
> Nice work on adding the test, about the jest issue is it something we can try to fix? is there an error message a failure or it just does not work as expected ( what did we change that could affect it?)

After adding the test for legacy sdk generators, the jest failed with this errors: 
`Jest: Coverage data for ./generators/bdk/java/index.js was not found.`
It still works fine if I remove the test on legacy sdk

**Review by symphony-youri — APPROVED** [review]

**Pull request merged**
