### PR TITLE
PLAT-10817: added ssl truststore to python BDK projects

### PR DESCRIPTION
**Pull request by symphony-elias**
### Ticket
PLAT-10817

### Description
Added ssl truststore to python BDK projects

### Checklist
- [x] Referenced a ticket in the PR title and in the corresponding section
- [x] Filled properly the description and dependencies, if any
- [x] Public functions properly commented

### CODE REVIEW

**Review by symphony-youri — APPROVED** [review]
Do we do the same for the Java BDK 2.0 generated projects?

Having a custom trust store is so sad, why can't we have proper certificates :'(... (I know I already argued against this change when we had to update the truststore for the legacy BDKs)

**Comment by symphony-elias** [comment]
> Do we do the same for the Java BDK 2.0 generated projects?
> 
> Having a custom trust store is so sad, why can't we have proper certificates :'(... (I know I already argued against this change when we had to update the truststore for the legacy BDKs)

No we don't have it for the Java BDK2.0 generated projects. This is specific to Python and MacOS X, see : https://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify
This has been documented here: https://github.com/SymphonyPlatformSolutions/symphony-api-client-python/blob/2.0/docsrc/markdown/faq.md

**Comment by symphony-youri** [comment]
> > Do we do the same for the Java BDK 2.0 generated projects?
> > Having a custom trust store is so sad, why can't we have proper certificates :'(... (I know I already argued against this change when we had to update the truststore for the legacy BDKs)
> 
> No we don't have it for the Java BDK2.0 generated projects. This is specific to Python and MacOS X, see : https://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify
> This has been documented here: https://github.com/SymphonyPlatformSolutions/symphony-api-client-python/blob/2.0/docsrc/markdown/faq.md
> So I don't know if we should do it or not. WDYT @symphony-thibault ?

Ok if we have an issue with Python/Mac let's see if this approach helps and go with that
We can always revise that in the future and drop the truststore.

**Comment by symphony-thibault** [comment]
I don't think we've ever had any feedback on the Java side. So let's keep it as it is for now.

**Pull request merged**
